/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cluster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cluster overview
         * @description Returns cluster health, node counts, storage usage, throughput history, and disk usage distribution.
         */
        get: operations["getClusterSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List storage nodes
         * @description Returns a paginated list of storage nodes with optional search, sort, and filter.
         */
        get: operations["getNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cluster events
         * @description Returns the event log, optionally filtered by severity.
         */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cluster configuration
         * @description Returns the current cluster configuration.
         */
        get: operations["getConfig"];
        put?: never;
        /**
         * Update cluster configuration
         * @description Partially updates the cluster configuration. Only provided fields are changed.
         */
        post: operations["updateConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List jobs
         * @description Returns all cluster jobs (queued, running, completed, failed, cancelled).
         */
        get: operations["getJobs"];
        put?: never;
        /**
         * Create a new job
         * @description Creates a new cluster job (rebalance, pool expansion, or health check).
         */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel a job
         * @description Cancels a queued or running job.
         */
        delete: operations["cancelJob"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        NodeStatus: "healthy" | "degraded" | "offline";
        StorageNode: {
            /** @example node-0042 */
            id: string;
            /** @example storage-node-042 */
            hostname: string;
            status: components["schemas"]["NodeStatus"];
            /** @example 67.3 */
            diskUsagePercent: number;
            /** @example 245.8 */
            ioThroughputMBps: number;
            /** Format: date-time */
            lastHeartbeat: string;
        };
        ThroughputDataPoint: {
            /** Format: date-time */
            timestamp: string;
            readMBps: number;
            writeMBps: number;
        };
        DiskUsageBucket: {
            /** @example 50-75% */
            range: string;
            count: number;
        };
        ClusterSummary: {
            totalNodes: number;
            activeNodes: number;
            healthyNodes: number;
            degradedNodes: number;
            offlineNodes: number;
            storageUsedTB: number;
            storageTotalTB: number;
            /** @enum {string} */
            clusterHealth: "green" | "yellow" | "red";
            throughputHistory: components["schemas"]["ThroughputDataPoint"][];
            diskUsageDistribution: components["schemas"]["DiskUsageBucket"][];
        };
        /** @enum {string} */
        EventSeverity: "info" | "warning" | "error";
        /** @enum {string} */
        EventType: "node_joined" | "node_failure" | "disk_capacity_warning" | "storage_pool_expanded";
        ClusterEvent: {
            id: string;
            /** Format: date-time */
            timestamp: string;
            type: components["schemas"]["EventType"];
            severity: components["schemas"]["EventSeverity"];
            message: string;
            nodeId?: string;
        };
        StorageTarget: {
            id: string;
            path: string;
            capacityTB: number;
            enabled: boolean;
        };
        ClusterConfig: {
            replicationFactor: number;
            metadataServers: string[];
            maintenanceMode: boolean;
            storageTargets: components["schemas"]["StorageTarget"][];
        };
        ClusterConfigUpdate: {
            replicationFactor?: number;
            metadataServers?: string[];
            maintenanceMode?: boolean;
            storageTargets?: components["schemas"]["StorageTarget"][];
        };
        /** @enum {string} */
        JobType: "rebalance" | "pool_expansion" | "health_check";
        /** @enum {string} */
        JobStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        Job: {
            id: string;
            type: components["schemas"]["JobType"];
            name: string;
            status: components["schemas"]["JobStatus"];
            progress: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            error?: string;
        };
        PaginatedNodes: {
            data: components["schemas"]["StorageNode"][];
            total: number;
            page: number;
            pageSize: number;
            totalPages: number;
        };
        Error: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getClusterSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cluster summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterSummary"];
                };
            };
        };
    };
    getNodes: {
        parameters: {
            query?: {
                /** @description Filter nodes by ID or hostname */
                search?: string;
                /** @description Column to sort by */
                sortBy?: "id" | "hostname" | "status" | "diskUsagePercent" | "ioThroughputMBps" | "lastHeartbeat";
                /** @description Sort direction */
                sortDir?: "asc" | "desc";
                /** @description Page number (1-based) */
                page?: number;
                /** @description Number of items per page */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated node list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNodes"];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: {
                /** @description Filter by severity level */
                severity?: "info" | "warning" | "error";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterEvent"][];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cluster config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterConfig"];
                };
            };
        };
    };
    updateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterConfigUpdate"];
            };
        };
        responses: {
            /** @description Updated config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterConfig"];
                };
            };
        };
    };
    getJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    type: components["schemas"]["JobType"];
                };
            };
        };
        responses: {
            /** @description Created job */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Job cannot be cancelled (already finished) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
